baseURL = "https://hdu.homeboyc.cn"

languageCode = "zh-cn"
DefaultContentLanguage = "zh"
title = "杭电生存指北"
theme = "hugo-theme-techdoc"

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

# Required to get well formatted code blocks
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

[params]

    # Source Code repository section
    description = "如何在杭电活下去"
    github_repository = "https://github.com/surviveInHDU/SurviveInHDU.github.io"
    version = "2021.1"

    # Documentation repository section
    # documentation repository (set "Edit on Github" link to documentation repository)
    github_doc_repository = "https://github.com/surviveInHDU/SurviveInHDU.github.io"

    # Analytic section
    google_analytics_id = "" # Your Google Analytics tracking id
    tag_manager_container_id = "" # Your Google Tag Manager container id
    google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    title = "Hugo Techdoc Theme"
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = ""

    # (Optional, default 6) Set how many table of contents levels to be showed on page.
    # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
    # You can also specify this parameter per page in front matter.
    geekdocToC = 1

    # (Optional, default static/brand.svg) Set the path to a logo for the Geekdoc
    # relative to your 'static/' folder.
    geekdocLogo = "logo.svg"

    # (Optional, default false) Render menu from data file im 'data/menu/main.yaml'.
    geekdocMenuBundle = true

    # (Optional, default true) Show a breadcrumb navigation bar at the top of each docs page.
    # You can also specify this parameter per page in front matter.
    geekdocBreadcrumb = true

    # (Optional, default none) Set source repository location. Used for 'Edit this page' links.
    # You can also specify this parameter per page in front matter.
    # geekdocRepo = "https://github.com/thegeeklab/hugo"

    # (Optional, default none) Enable 'Edit this page' links. Requires 'GeekdocRepo' param
    # and path must point to 'content' directory of repo.
    # You can also specify this parameter per page in front matter.
    # geekdocEditPath = "edit/master/exampleSite/content"

    # (Optional, default true) Enables search function with flexsearch.
    # Index is built on the fly and might slowdown your website.
    geekdocSearch = false

    # (Optional, default false) Display search results with the parent folder as prefix. This
    # option allows you to distinguish between files with the same name in different folders.
    # NOTE: This parameter only applies when 'geekdocSearch = true'.
    geekdocSearchShowParent = false

    # (Optional, default none) Add a link to your Legal Notice page to the site footer.
    # It can be either a remote url or a local file path relative to your content directory.
    # geekdocLegalNotice = "/content/LegalNotic"

    # (Optional, default none) Add a link to your Privacy Policy page to the site footer.
    # It can be either a remote url or a local file path relative to your content directory.
    # geekdocPrivacyPolicy = "/privacy"

    # (Optional, default true) Add an anchor link to headlines.
    geekdocAnchor = true

    # (Optional, default true) Copy anchor url to clipboard on click.
    geekdocAnchorCopy = false

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    menu_exclusion = [
        "archives",
        "archive",
        "blog",
        "entry",
        "post",
        "posts",
    ]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    algolia_search_enable = true
    algolia_indexName = "hugo-demo-techdoc"
    algolia_appId = "7W4SAN4PLK"
    algolia_apiKey = "cbf12a63ff72d9c5dc0c10c195cf9128" # Search-Only API Key

# Global menu section
# See https://gohugo.io/content-management/menus/
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

#    [[menu.main]]
#        name = "Twitter"
#        url = "https://twitter.com/thingsym"
#        weight = 2

# Markup configure section
# See https://gohugo.io/getting-started/configuration-markup/
[markup]
    defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
        unsafe= false
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 6
        ordered = false

[outputs]
    home = ["HTML", "RSS", "Algolia"]

# Algolia Search configure section
[outputFormats.Algolia]
    baseName = "algolia"
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true

[params.algolia]
    vars = [
        "title",
        "summary",
        "content",
        "date",
        "publishdate",
        "description",
        "permalink",
        "keywords",
        "lastmod",
    ]
    params = [
        "tags",
        "categories",
    ]
